* Fundamental libray for Scientific Computation in Python
* Provides support for Arrays, Matrices and many other mathematical functions

In [1]:
!pip install numpy

In [5]:
import numpy as np

## Create arrays using numpy
# Create 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1, 5) #1 Row and 5 Columns


array([[1, 2, 3, 4, 5]])

In [8]:
# Create 1R 5C array
arr3 = np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [14]:
# 2D array
# Creating 2R 5C Array
arr4 = np.array([[1,2,3,4,5], [5,4,3,2,1]])
print(arr4)
arr4.shape

[[1 2 3 4 5]
 [5 4 3 2 1]]


(2, 5)

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Attributes of numppy

arr = np.array([[1,2,3,4], [5,6,7,8]])

print('Array - ', arr)
print('Shape of array - ', arr.shape)
print('Num or Dimensions - ', arr.ndim)
print('Size (Num of elements) - ', arr.size)
print('Data Type - ', arr.dtype)
print('Item Size (in bytes) - ', arr.itemsize)

Array -  [[1 2 3 4]
 [5 6 7 8]]
Shape of array -  (2, 4)
Num or Dimensions -  2
Size (Num of elements) -  8
Data Type -  int64
Item Size (in bytes) -  8


In [36]:
## Numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# eleementwise addition
print('Addition', arr1+arr2)

# elementwise subtraction
print('Addition', arr1-arr2)

# elementwise multiplication
print('Addition', arr1*arr2)

# elementwise division
print('Addition', arr1/arr2)

Addition [11 22 33 44 55]
Addition [ -9 -18 -27 -36 -45]
Addition [ 10  40  90 160 250]
Addition [0.1 0.1 0.1 0.1 0.1]


In [39]:
arr1 = np.array([1,2,3,4,5])

#square root
print(np.sqrt(arr1))

# exponential 
print(np.exp(arr1))

# sine
print(np.sin(arr1))

# natural log
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [52]:
# Array slicing and indexing

arr1 = np.array([[1,2,3,4], [5,6,7,8], [7,8,9,0]])
print('Array: \n', arr1)

arr1.shape


Array: 
 [[1 2 3 4]
 [5 6 7 8]
 [7 8 9 0]]


(3, 4)

In [56]:
# get 1
print('slicing 1', arr1[0][0])
print(arr1[0:2])

# getting 7 8 and 9 0
arr1[1:, 2:]

slicing 1 1
[[1 2 3 4]
 [5 6 7 8]]


array([[7, 8],
       [9, 0]])

In [68]:
# getting 3 4 and 7 8
arr1[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [63]:
# get 2 3 4 & 6 7 8
arr1[0:2, 1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [72]:
arr1
arr1[0:2, 1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [84]:
# get 6 7 & 8 9
arr1

arr1[1:, 1:3]

array([[6, 7],
       [8, 9]])

In [91]:
# get 1 2 & 5 6
arr1

arr1[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [93]:
## modify elements
arr1[0, 0] = 100
arr1

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  7,   8,   9,   0]])

In [94]:
arr1[1:] = 100
arr1

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [98]:
## Statistical Concept
# Normalization - to have a mean of 0 and deviation of 1

data = np.array([1,2,3,4,5])

# calculate mean and standard deviation
mean = np.mean(data)
std_deviation = np.std(data)
print(f'Mean - {mean} and std - {std_deviation}')

# normalized data
normalized_data = (data - mean) / std_deviation
print(f'Normalized data - {normalized_data}')

Mean - 3.0 and std - 1.4142135623730951
Normalized data - [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [100]:
## calculating mean, median and mode

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)

print(f'Mean - {mean}\n median - {median}\n std_dev - {std_dev} \n variance - {variance}')

Mean - 3.0
 median - 3.0
 std_dev - 1.4142135623730951 
 variance - 2.0


In [107]:
# logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data < 8)]


array([6, 7])